name: "Docker Server Image"

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:
    inputs:
      repository_url:
        required: true
        default: 'simon824/incubator-hugegraph-toolchain'
      repository_branch:
        required: true
        default: 'master'
      image_url:
        required: true
        default: 'simon824/hugegraph-hubble'
      tag:
        required: true
        default: 'test'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # TODO: support auto tag/label the images by action
      # Refer: https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
      IMAGE_URI: ${{ inputs.image_url }}:${{ inputs.tag }}
    steps:
      # Used for build X64 & ARM images together
      # Refer: https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.docker_registry_url }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository_url }}
          ref: ${{ inputs.repository_branch }}
          fetch-depth: 2
          
      - name: Package
        run: |
          cd hugegraph-hubble
          mvn package -e -B -ntp -DskipTests -Dmaven.javadoc.skip=true
          pwd && ls -lth
#       - name: Build X86 Image
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           tags: ${{ env.IMAGE_URI }}
#           push: true
#           cache-from: type=gha
#           cache-to: type=gha,mode=max
      
#       - name: Test X86 Image
#         run: |
#           docker version
#           docker images
#           docker run -itd $IMAGE_URI
#           sleep 15s
#           docker ps -a
#           sleep 15s
#           docker ps -a

      - name: Build ARM & Push all
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./hugegraph-hubble/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_URI }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
