name: Publish hugegraph-computer image

on:
#   schedule:
#     - cron:  '50 0-23 * * *'
  workflow_dispatch:
    inputs:
      repository_url:
        required: true
        default: 'apache/hugegraph-computer'
      repository_branch:
        required: true
        default: 'master'
      computer_image_url:
        required: true
        default: 'hugegraph/hugegraph-computer:latest'
      operator_image_url:
        required: true
        default: 'hugegraph/hugegraph-computer-operator:latest'
      docker_registry_url:
        required: false
        default: ''
env:
  repository_url: apache/hugegraph-computer
  repository_branch: master
  computer_image_url: hugegraph/hugegraph-computer:latest
  operator_image_url: hugegraph/hugegraph-computer-operator:latest
  docker_registry_url: ""

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Reset env
        if: github.event_name == 'workflow_dispatch'
        run: |
         echo "repository_url=${{ github.event.inputs.repository_url }}" >> $GITHUB_ENV
         echo "repository_branch=${{ github.event.inputs.repository_branch }}" >> $GITHUB_ENV
         echo "computer_image_url=${{ github.event.inputs.computer_image_url }}" >> $GITHUB_ENV
         echo "operator_image_url=${{ github.event.inputs.operator_image_url }}" >> $GITHUB_ENV
         echo "docker_registry_url=${{ github.event.inputs.docker_registry_url }}" >> $GITHUB_ENV
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.docker_registry_url }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ env.repository_url }}
          ref: ${{ env.repository_branch }}
          fetch-depth: 2
          
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2          
      
      - name: Build images
        env:
          TRAVIS_DIR: computer-dist/src/assembly/travis
        run: $TRAVIS_DIR/build-images.sh ${{ env.computer_image_url }} ${{ env.operator_image_url }}

      - name: Docker images
        run: docker images

      - name: Publish
        run: |
          docker push ${{ env.computer_image_url }}
          docker push ${{ env.operator_image_url }}
          
